game_settings:
  N: 6  # Size of the matrix (N x N upper triangular matrix)
  gate: 0  # Points for each action (added each time a column pair is selected)
  layer: 0.1  # Penalty points when reusing columns included in the set. N//2
  MAX_STEPS: 25  # Maximum number of steps to forcibly end the game. (NC2)**(2N) if 3-正則


mcts_settings:
  c_puct: 5
  epsilon: 0.5
  dirichlet_alpha: 0.5
  num_mcts_simulations: 100 # 100以上
  max_depth: 25 # N * N
  tau_threshold: 10

network_settings:
  n_blocks: 12
  filters: 192
  use_bias: False
  learning_rate: 0.0006

training_settings:
  num_cpus: 0
  num_gpus: 1
  n_episodes: 500
  buffer_size: 500
  batch_size: 64
  epochs_per_update: 50
  update_period: 50
  save_period: 50
  eval_period: 50
