game_settings:
  N: 6
  gate: 0.2        # 各アクションに対するペナルティ
  layer: 0.1       # カラムの再利用に対するペナルティ（正の値に設定）
  MAX_STEPS: 40

mcts_settings:
  c_puct: 2.0
  epsilon: 0.4
  dirichlet_alpha: 0.6
  num_mcts_simulations: 200
  max_depth: 40
  tau_threshold: 10  # 初期の手数での探索性を制御

network_settings:
  n_blocks: 12
  filters: 192
  use_bias: False
  learning_rate: 0.0006

training_settings:
  num_cpus: 8
  num_gpus: 0
  n_episodes: 1000
  buffer_size: 1500
  batch_size: 128
  epochs_per_update: 50
  update_period: 50
  save_period: 50
  eval_period: 100  # 評価の頻度を設定