game_settings:
  N: 6
  gate: 0.    # ペナルティの値を小さく調整
  layer: 0.    # 同上
  MAX_STEPS: 25

mcts_settings:
  c_puct: 2.0
  epsilon: 0.4
  dirichlet_alpha: 0.6
  num_mcts_simulations: 200
  max_depth: 40
  tau_threshold: 10

network_settings:
  n_blocks: 12
  filters: 192
  use_bias: False
  learning_rate: 0.0006

training_settings:
  num_cpus: 8
  num_gpus: 0
  n_episodes: 700
  buffer_size: 700
  batch_size: 64
  epochs_per_update: 50
  update_period: 50
  save_period: 50
  eval_period: 100

