game_settings:
  N: 7  # Size of the matrix (N x N upper triangular matrix)
  a: 1  # Points for each action (added each time a column pair is selected)
  b: 8  # Penalty points when reusing columns included in the set. N//2
  MAX_STEPS: 25  # Maximum number of steps to forcibly end the game. (NC2)**(2N) if 3-正則


mcts_settings:
  c_puct: 5
  epsilon: 0.5
  dirichlet_alpha: 0.5
  num_mcts_simulations: 100 # 100以上
  max_depth: 25 # N * N

network_settings:
  n_blocks: 20
  filters: 256
  use_bias: False
  learning_rate: 0.0004

training_settings:
  num_cpus: 8
  n_episodes: 700
  buffer_size: 700
  batch_size: 64
  epochs_per_update: 50
  update_period: 50
  save_period: 50