game_settings:
  N: 10
  gate: 0.01
  layer: 0.1
  MAX_STEPS: 50

mcts_settings:
  c_puct: 5
  epsilon: 0.5
  dirichlet_alpha: 0.5
  num_mcts_simulations: 200
  max_depth: 50
  tau_threshold: 10

network_settings:
  n_blocks: 16
  filters: 256
  use_bias: False
  learning_rate: 0.0005

training_settings:
  num_cpus: 0
  num_gpus: 1  
  n_episodes: 700
  buffer_size: 700
  batch_size: 64
  epochs_per_update: 50
  update_period: 50
  save_period: 50
  eval_period: 100
